const videoClientKey=crypto.randomUUID();let activeLiveTicket=null,lastLiveConfirmation=0,liveConfirming=false;let liveReceivingId=null,lastVideoProgress=0,lastVideoTime=-1;
'use strict';
let deviceSelection=new Set(),bulkRemoving=false;
const center=[-13.2582793655,-58.7325993091];
let cameras=[],units=[],sectors=[],devicePage=1,batchToken=null,importToken=null;
let batchGeneration=0,importGeneration=0;
let alertData=null,maintenanceData=[],activeAlert=null,maintenanceCamera=null;let overviewData=null;let refreshing=false;let reportLast=0,reportGeneration=0,reportData=null;
let authToken=sessionStorage.getItem("scheffer-token")||"";
async function api(path,options={}){const response=await fetch("/api"+path,{...options,headers:{"Content-Type":"application/json",Authorization:"Bearer "+authToken,...options.headers}});if(!response.ok){if(response.status===401){sessionStorage.removeItem("scheffer-token");authToken="";}const error=await response.json().catch(()=>({}));const failure=new Error(typeof error.detail==="string"?error.detail:"Falha na API ("+response.status+"). Verifique login e dados.");failure.status=response.status;throw failure;}return response.json();}
async function load(){if(refreshing)return;refreshing=true;try{const snap=await api("/snapshot?state_filter="+encodeURIComponent($("alert-filter").value));units=snap.units;sectors=snap.sectors;cameras=snap.cameras;if(selected&&cameras.some(c=>c.id===selected&&c.is_free)){stopLive();$('viewer').hidden=true;}if(selected&&!cameras.some(c=>c.id===selected)){stopLive();$('viewer').hidden=true;selected=null;}overviewData=snap.overview;await loadAlerts(snap,false);render();renderOverview();const monitor=snap.monitor;$('monitor-summary').textContent=monitor.running?'Monitor ativo · '+monitor.configured+' configuradas · '+monitor.in_progress+'/'+monitor.workers+' verificações · '+(monitor.stale||0)+' sem verificação recente':'Monitor '+(monitor.enabled?'iniciando':'desativado');const events=snap.events;$('events-table').innerHTML=events.map(e=>'<tr><td>'+new Date(e.timestamp*1000).toLocaleString('pt-BR')+'</td><td>'+escapeText(e.name)+'</td><td>'+escapeText(names[e.previous]||e.previous)+'</td><td>'+escapeText(names[e.status]||e.status)+'</td><td>'+escapeText(e.diagnostic)+'</td></tr>').join('')||'<tr><td colspan="5">Nenhuma mudança registrada.</td></tr>';if(!$('dashboard-page').hidden&&Date.now()-reportLast>30000)loadReport();}catch(e){toast(e.message);if(!authToken&&!$('login-dialog').open)$('login-dialog').showModal();}finally{refreshing=false;}}

const $=id=>document.getElementById(id),escapeText=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={online:'Online',offline:'Offline',unknown:'Não verificada',free:'Canal livre'};
let lastMapSignature=null;
let expandedCameraGroup=null;let map,markers,draftMarker=null,positioning=false,positionCameraId=null,positionSaving=false,basemaps={},activeBasemap=null,basemapTimer=null,selected=null,editing=null,toastTimer,hls=null,playGeneration=0,liveAbort=null;
function status(c){return '<span class="status-label"><span class="dot '+c.status+'"></span>'+names[c.status]+(c.verification_stale?' · verificação vencida':'')+'</span>';}
function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4000);}
function page(name){if(name!=='map'&&positioning)closePositioning();if(name!=='map'&&!$('viewer').hidden){stopLive();$('viewer').hidden=true;}document.querySelectorAll('.page').forEach(p=>p.hidden=p.id!==name+'-page');document.querySelectorAll('nav [data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===name));if(name==='map'&&map)setTimeout(()=>map.invalidateSize(),0);if(name==='organization')renderOrganization();if(name==='dashboard'&&authToken)loadReport();if(name==='alerts'&&authToken)loadAlerts();}
function filtered(){const q=$('search').value.trim().toLocaleLowerCase('pt-BR'),uid=$('filter-unit').value,sector=$('filter-sector').value,recorder=$('filter-recorder').value,maker=$('filter-manufacturer').value,state=$('filter-status').value,maintenance=$('filter-maintenance').value;return cameras.filter(c=>{const inMaintenance=maintenanceData.some(m=>m.camera_id===c.id);return (c.name+' '+c.manufacturer+' '+c.ip+' '+c.model+' '+c.unit_name+' '+c.sector_name+' '+c.recorder_name+' '+c.channel).toLocaleLowerCase('pt-BR').includes(q)&&(!$('only-online').checked||c.status==='online')&&(!uid||c.unit_id===Number(uid))&&(!sector||c.sector_id===Number(sector))&&(!recorder||recorderKey(c)===recorder)&&(!maker||c.manufacturer===maker)&&(!state||c.status===state)&&(!maintenance||(maintenance==='yes'?inMaintenance:!inMaintenance));});}
function render(){updateInventoryFilters();const online=cameras.filter(c=>c.status==='online').length,offline=cameras.filter(c=>c.status==='offline').length,unknown=cameras.length-online-offline;
 $('totals').innerHTML='<span><b>'+cameras.length+'</b> câmeras</span><span><i class="dot online"></i> '+online+' online</span><span><i class="dot offline"></i> '+offline+' offline</span><span><i class="dot free"></i> '+cameras.filter(c=>c.is_free).length+' livres</span>';$('unit-count').textContent=cameras.length;
 const visible=filtered();$('unit-count').textContent=visible.length;
 $('camera-tree').innerHTML=units.map(u=>{const items=visible.filter(c=>c.unit_id===u.id&&!c.is_free);if(!items.length)return '';return '<details open><summary>'+escapeText(u.name)+' <span>'+items.length+'</span></summary>'+items.map(c=>'<button class="tree-camera '+(selected===c.id?'selected':'')+'" data-camera="'+c.id+'"><span>▣</span><span class="camera-name">'+escapeText(c.name)+'</span><i class="dot '+c.status+'"></i></button>').join('')+'</details>';}).join('')||'<p>Nenhuma câmera encontrada.</p>';
 const pages=Math.max(1,Math.ceil(visible.length/50));devicePage=Math.min(devicePage,pages);$('inventory-count').textContent=visible.length+' dispositivos no filtro · '+cameras.length+' cadastrados';$('device-pagination-label').textContent='Página '+devicePage+' de '+pages;$('device-prev').disabled=devicePage===1;$('device-next').disabled=devicePage===pages;
 $('device-table').innerHTML=visible.slice((devicePage-1)*50,devicePage*50).map(c=>'<tr><td><input type="checkbox" data-select-device="'+c.id+'" aria-label="Selecionar '+escapeText(c.name)+'" '+(deviceSelection.has(c.id)?'checked':'')+' '+(bulkRemoving?'disabled':'')+'></td><td>'+escapeText(c.name)+'<small>'+escapeText(c.unit_name)+(c.sector_name?' · '+escapeText(c.sector_name):'')+'</small></td><td>'+escapeText(c.recorder_name||(c.device_type==='nvr'?'Gravador sem nome':'Câmera direta'))+'<small>'+escapeText(c.manufacturer+' · '+c.model)+'</small></td><td>'+escapeText(c.ip)+':'+c.port+'<small>Canal '+c.channel+'</small></td><td>'+status(c)+'<label class="channel-free-toggle"><input type="checkbox" data-free-channel="'+c.id+'" '+(c.is_free?'checked':'')+'> Canal livre</label>'+(maintenanceData.some(m=>m.camera_id===c.id)?'<small class="maintenance-badge">Em manutenção</small>':'')+'</td><td><div class="actions"><button data-camera="'+c.id+'">Abrir</button><button data-edit="'+c.id+'">Editar</button><button data-maintenance="'+c.id+'">Manutenção</button><button class="danger" data-remove="'+c.id+'">Remover</button></div></td></tr>').join('')||'<tr><td colspan="6">Nenhuma câmera encontrada.</td></tr>';
 updateDeviceSelection(visible);
 if(selected){const current=cameras.find(c=>c.id===selected);if(current)renderCameraDetails(current);}
 updateReportCameras();renderOverview();
 if(markers&&!$('map-page').hidden)renderMapGroups(visible);
 if(positioning)refreshPositionCameraOptions();
}
function openCamera(id){const c=cameras.find(x=>x.id===id);if(!c)return;if(c.is_free){toast('Canal livre. Desmarque a opção para ativar o vídeo e o monitoramento.');return;}selected=id;page('map');$('viewer').hidden=false;$('viewer-title').textContent=c.name;$('viewer-status').innerHTML='<i class="dot '+(c.status==='online'?'online':c.status==='offline'?'offline':'unknown')+'"></i>';$('viewer-status').setAttribute('aria-label',names[c.status]||'Não verificada');$('viewer-status').title=names[c.status]||'Não verificada';renderCameraDetails(c);$('video-title').textContent=c.status==='online'?'Prévia do player':names[c.status];$('video-message').textContent=c.status==='online'?'Conectando ao stream cadastrado.':c.status==='offline'?'Falha de comunicação.':'Aguardando verificação de conexão.';if(map)map.panTo([c.lat,c.lng]);render();startLive(id);}
function form(id=null){editing=id;$('remove-camera').hidden=!id;const c=cameras.find(x=>x.id===id)||{name:'',manufacturer:'Intelbras',model:'',ip:'',port:554,channel:1,lat:center[0],lng:center[1],status:'unknown',device_type:'nvr',username:'',stream:'secondary',rtsp_path:'',unit_id:Number($('filter-unit').value)||1,sector_id:0,recorder_name:''};setDeviceOrganization(c);$('device-is-free').checked=!!c.is_free;$('form-title').textContent=id?'Editar câmera':'Nova câmera';for(const [k,v]of Object.entries(c)){if($('device-form').elements[k])$('device-form').elements[k].value=v;}$('device-form').elements.password.value='';$('test-result').textContent=c.has_password?'Senha armazenada. Deixe vazio para mantê-la.':'';$('device-dialog').showModal();}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.page)page(b.dataset.page);if(b.dataset.camera)openCamera(Number(b.dataset.camera));if(b.dataset.edit)form(Number(b.dataset.edit));if(b.dataset.remove)removeCamera(Number(b.dataset.remove));if(b.dataset.maintenance)maintenanceForm(Number(b.dataset.maintenance));if(b.dataset.alert)alertForm(Number(b.dataset.alert));});
$('search').addEventListener('input',render);$('only-online').addEventListener('change',render);$('close-viewer').onclick=()=>{stopLive();$('viewer').hidden=true;$('viewer').classList.remove('expanded');};$('fullscreen').onclick=async()=>{const panel=$('player-panel'),video=$('live-video');try{if(document.fullscreenElement){await document.exitFullscreen();return;}if(panel.requestFullscreen){await panel.requestFullscreen();return;}if(video.webkitEnterFullscreen&&!video.hidden){video.webkitEnterFullscreen();return;}}catch(error){toast('Tela cheia indisponível no navegador. Janela ampliada.');}$('viewer').classList.toggle('expanded');};document.addEventListener('fullscreenchange',()=>{$('fullscreen').setAttribute('aria-label',document.fullscreenElement?'Sair da tela cheia':'Abrir vídeo em tela cheia');});$('new-camera').onclick=()=>form();$('close-form').onclick=()=>$('device-dialog').close();$('edit-selected').onclick=()=>form(selected);$('center-map').onclick=()=>{if(map){const u=units.find(u=>u.id===Number($('filter-unit').value));map.setView(u?[u.lat,u.lng]:center,15);}else toast('Cartografia indisponível. Verifique sua conexão com a internet.');};
$('test-camera').onclick=async()=>{if(!editing){$('test-result').textContent='Salve o cadastro antes de testar.';return;}$('test-camera').disabled=true;$('test-result').textContent='Testando cadastro salvo…';try{const r=await api('/cameras/'+editing+'/test',{method:'POST'});$('test-result').textContent=r.diagnostic+(r.codec?' Codec: '+r.codec:'');await load();}catch(e){$('test-result').textContent=e.message;}finally{$('test-camera').disabled=false;}};
$('device-form').addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));if(!/^((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)\.){3}(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)$/.test(data.ip)){$('test-result').textContent='Informe um endereço IPv4 válido.';return;}data.name=data.name.trim();if(!data.name){$('test-result').textContent='Informe o nome da câmera.';return;}for(const k of ['port','channel','lat','lng'])data[k]=Number(data[k]);delete data.status;data.is_free=$('device-is-free').checked;data.unit_id=Number(data.unit_id);data.sector_id=Number(data.sector_id);try{const saved=await api(editing?'/cameras/'+editing:'/cameras',{method:editing?'PUT':'POST',body:JSON.stringify(data)});$('device-form').elements.password.value='';$('device-dialog').close();await load();if(selected===saved.id)openCamera(saved.id);toast('Cadastro salvo no banco de dados.');}catch(error){$('test-result').textContent=error.message;}});
try{
 if(typeof L==='undefined')throw Error('Leaflet unavailable');
 map=L.map('map',{zoomControl:false,maxZoom:21}).setView(center,17);
 L.control.zoom({position:'topright'}).addTo(map);markers=L.layerGroup().addTo(map);
 basemaps.streets=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxNativeZoom:19,maxZoom:21,attribution:'© <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> contributors'});
 basemaps.satellite=L.tileLayer('https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxNativeZoom:16,maxZoom:21,attribution:'Tiles © Esri — Source: Esri, Maxar, Earthstar Geographics, and the GIS User Community'});
 Object.values(basemaps).forEach(layer=>{layer.on('tileload',()=>{if(layer===activeBasemap){layer.schefferLoaded=true;$('map-fallback').hidden=true;clearTimeout(basemapTimer);}});layer.on('tileerror',()=>{if(layer===activeBasemap)$('map-imagery-status').textContent='Falha ao carregar imagens. Verifique internet ou alterne para Ruas.';});});
 let preferred='streets';
 setBasemap(preferred==='streets'?'streets':'satellite');
 map.on('zoomend',()=>{expandedCameraGroup=null;renderMapGroups(filtered());});
 map.on('moveend',()=>renderMapGroups(filtered()));
 map.on('click',e=>{if(expandedCameraGroup){expandedCameraGroup=null;renderMapGroups(filtered());}if(positioning&&!positionSaving&&positionCameraId)setDraftPosition(e.latlng.lat,e.latlng.lng);});
}catch(e){$('map-fallback').hidden=false;}

render();

document.getElementById("login-form").addEventListener("submit",async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.target));try{const result=await api("/login",{method:"POST",body:JSON.stringify(body)});authToken=result.token;sessionStorage.setItem("scheffer-token",authToken);document.getElementById("login-dialog").close();await load();}catch(error){document.getElementById("login-error").textContent=error.message;}});
document.getElementById("logout").onclick=async()=>{try{await api("/logout",{method:"POST"});}finally{sessionStorage.removeItem("scheffer-token");location.reload();}};
if(authToken)load();else document.getElementById("login-dialog").showModal();
function stopLive(notify=true){playGeneration++;activeLiveTicket=null;lastLiveConfirmation=0;liveReceivingId=null;lastVideoProgress=0;lastVideoTime=-1;if(notify&&authToken)fetch('/api/live-cancel',{method:'POST',headers:{Authorization:'Bearer '+authToken,'X-Video-Client':videoClientKey},keepalive:true}).catch(()=>{});if(liveAbort){liveAbort.abort();liveAbort=null;}if(hls){hls.destroy();hls=null;}const v=$('live-video');v.pause();v.removeAttribute('src');v.load();v.hidden=true;$('player-text').hidden=false;}
async function startLive(id){stopLive(false);const generation=playGeneration;$('video-title').textContent='Conectando ao canal…';$('video-message').textContent='O primeiro carregamento pode levar alguns segundos.';try{const result=await openReadyLive(id,generation);if(generation!==playGeneration)return;activeLiveTicket=result.url.split('/')[3];const v=$('live-video');if(typeof Hls!=='undefined'&&Hls.isSupported()){hls=new Hls({manifestLoadingTimeOut:30000,manifestLoadingMaxRetry:4,manifestLoadingRetryDelay:2000,levelLoadingTimeOut:30000,fragLoadingTimeOut:30000});hls.loadSource(result.url);hls.attachMedia(v);hls.on(Hls.Events.MANIFEST_PARSED,()=>{if(generation!==playGeneration)return;v.hidden=false;$('player-text').hidden=true;v.play().catch(()=>{});});let mediaRecovery=false;hls.on(Hls.Events.ERROR,(_,data)=>{if(data.fatal&&generation===playGeneration){if(data.type===Hls.ErrorTypes.MEDIA_ERROR&&!mediaRecovery){mediaRecovery=true;hls.recoverMediaError();return;}stopLive();$('video-title').textContent='Vídeo indisponível';$('video-message').textContent='Falha no player ('+(data.details||data.type||'HLS')+'). Clique em reconectar. Se persistir, consulte os logs do serviço video.';}});}else if(v.canPlayType('application/vnd.apple.mpegurl')){v.src=result.url;v.hidden=false;$('player-text').hidden=true;v.play().catch(()=>{});}else throw Error('Player HLS indisponível. Verifique internet para carregar a biblioteca do player.');}catch(e){if(generation!==playGeneration)return;$('video-title').textContent='Não foi possível abrir o vídeo';$('video-message').textContent=e.message;}}

async function removeCamera(id){const camera=cameras.find(c=>c.id===id);if(!camera)return;if(!confirm('Remover o dispositivo "'+camera.name+'"? O cadastro e suas credenciais serão excluídos. Esta ação será registrada na auditoria.'))return;try{const result=await api('/cameras/'+id,{method:'DELETE'});if(selected===id){stopLive();$('viewer').hidden=true;selected=null;}if(editing===id){$('device-form').elements.password.value='';$('device-dialog').close();editing=null;}await load();toast(result.gateway_cleaned?'Dispositivo removido.':'Cadastro removido; limpeza do gateway pendente. Reinicie o serviço video.');}catch(error){toast(error.message);}}
$('remove-camera').onclick=()=>removeCamera(editing);
setInterval(()=>{if(authToken&&!document.hidden)load();},5000);
function updateReportCameras(){const select=$('report-camera'),previous=select.value,maker=$('report-maker').value;select.innerHTML='<option value="0">Todas as câmeras</option>'+cameras.filter(c=>!c.is_free&&(!maker||c.manufacturer===maker)).map(c=>'<option value="'+c.id+'">'+escapeText(c.name)+'</option>').join('');select.value=[...select.options].some(o=>o.value===previous)?previous:'0';}
function percent(n){return n===null?'Sem dados':n.toLocaleString('pt-BR',{maximumFractionDigits:1})+'%';}
function duration(seconds){const n=Math.round(seconds);if(n<60)return n+' s';const minutes=Math.floor(n/60),hours=Math.floor(minutes/60);return hours?hours+' h '+(minutes%60)+' min':minutes+' min';}
async function loadReport(){if(!authToken)return;const generation=++reportGeneration;reportLast=Date.now();$('report-error').textContent='Carregando indicadores…';const query=new URLSearchParams({hours:$('report-period').value,manufacturer:$('report-maker').value,camera_id:$('report-camera').value});try{const result=await api('/dashboard?'+query);if(generation!==reportGeneration)return;reportData=result;$('report-error').textContent='';$('report-window').textContent=new Date(result.start*1000).toLocaleString('pt-BR')+' a '+new Date(result.end*1000).toLocaleString('pt-BR')+' · '+result.camera_count+' câmeras atuais';$('report-stats').innerHTML=[['Disponibilidade observada',percent(result.availability),'Somente tempo com verificação válida'],['Cobertura do período',percent(result.coverage),'Sem verificação: '+duration(result.unknown_seconds)],['Tempo offline observado',duration(result.offline_seconds),result.offline_episodes+' episódios offline detectados']].map(x=>'<div class="stat">'+x[0]+'<b>'+x[1]+'</b><small>'+x[2]+'</small></div>').join('');$('report-table').innerHTML=result.rows.map(c=>'<tr><td>'+escapeText(c.name)+'<small>'+escapeText(c.manufacturer)+'</small></td><td>'+status(c)+'</td><td>'+percent(c.availability)+'</td><td>'+percent(c.coverage)+'</td><td>'+duration(c.offline_seconds)+'</td><td>'+c.offline_episodes+'</td></tr>').join('')||'<tr><td colspan="6">Nenhuma câmera no filtro selecionado.</td></tr>';drawReport();renderOverview();}catch(error){if(generation===reportGeneration){reportData=null;$('report-error').textContent=error.message;$('report-stats').innerHTML='';$('report-table').innerHTML='';$('report-chart').innerHTML='';renderOverview();}}}
function drawReport(){if(!reportData)return;const data=reportData.timeline,container=$('report-chart');if(!reportData.camera_count){container.innerHTML='<p class="muted">Nenhuma câmera no filtro selecionado.</p>';return;}const w=Math.max(280,container.clientWidth),h=250,left=38,right=10,top=20,bottom=52,pw=w-left-right,ph=h-top-bottom,bw=pw/data.length;let svg='<svg viewBox="0 0 '+w+' '+h+'" role="img" aria-label="Proporção do tempo online, offline e sem verificação em cada faixa do período"><title>Evolução da situação das câmeras</title>';for(const value of [0,50,100]){const y=top+ph*(1-value/100);svg+='<line x1="'+left+'" x2="'+(w-right)+'" y1="'+y+'" y2="'+y+'" stroke="#e1e8e3"/><text x="'+(left-7)+'" y="'+(y+4)+'" text-anchor="end">'+value+'%</text>';}data.forEach((b,i)=>{let y=top+ph;svg+='<g><title>'+escapeText(new Date(b.start*1000).toLocaleString('pt-BR'))+' · online '+percent(b.online_percent)+' · offline '+percent(b.offline_percent)+' · sem verificação '+percent(b.unknown_percent)+'</title>';for(const [key,color]of [['online_percent','#35aa65'],['offline_percent','#db4149'],['unknown_percent','#b4c0b7']]){const height=ph*b[key]/100;y-=height;svg+='<rect x="'+(left+i*bw+2)+'" y="'+y+'" width="'+Math.max(1,bw-4)+'" height="'+height+'" fill="'+color+'"/>';}svg+='</g>';});for(const [i,anchor]of [[0,'start'],[Math.floor(data.length/2),'middle'],[data.length-1,'end']]){const b=data[i],date=new Date(b.start*1000);const label=date.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'})+' '+date.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});const x=i===0?left:i===data.length-1?w-right:left+i*bw;svg+='<text x="'+x+'" y="'+(h-28)+'" text-anchor="'+anchor+'">'+label+'</text>';}svg+='<text x="'+(left+pw/2)+'" y="'+(h-6)+'" text-anchor="middle">Período · horário local</text></svg>';container.innerHTML=svg;}
['report-period','report-camera'].forEach(id=>$(id).addEventListener('change',loadReport));$('report-maker').addEventListener('change',()=>{updateReportCameras();loadReport();});$('report-refresh').onclick=loadReport;
new ResizeObserver(()=>{if(!$('dashboard-page').hidden)drawReport();}).observe($('report-chart'));
function ring(target,segments,caption,semi=false,centerText=null){const total=segments.reduce((a,b)=>a+b.value,0),r=semi?78:66,circumference=(semi?Math.PI:2*Math.PI)*r;let offset=0;let svg='<svg viewBox="0 0 200 '+(semi?125:180)+'" role="img" aria-label="'+escapeText(caption+': '+segments.map(s=>s.label+' '+s.value).join(', '))+'"><title>'+escapeText(caption)+'</title>';if(semi){svg+='<path d="M22 100 A78 78 0 0 1 178 100" fill="none" stroke="#dce3dd" stroke-width="28"/>';for(const segment of segments){if(total&&segment.value){const size=segment.value/total*circumference;svg+='<path d="M22 100 A78 78 0 0 1 178 100" fill="none" stroke="'+segment.color+'" stroke-width="28" stroke-dasharray="'+size+' '+circumference+'" stroke-dashoffset="'+(-offset)+'"/>';offset+=size;}}svg+='<text x="100" y="95" text-anchor="middle" class="ring-value">'+escapeText(centerText===null?String(total):centerText)+'</text>'; }else{svg+='<circle cx="100" cy="84" r="66" fill="none" stroke="#dce3dd" stroke-width="28"/>';for(const segment of segments){if(total&&segment.value){const size=segment.value/total*circumference;svg+='<circle cx="100" cy="84" r="66" fill="none" stroke="'+segment.color+'" stroke-width="28" transform="rotate(-90 100 84)" stroke-dasharray="'+size+' '+circumference+'" stroke-dashoffset="'+(-offset)+'"/>';offset+=size;}}svg+='<text x="100" y="83" text-anchor="middle" class="ring-value">'+escapeText(centerText===null?String(total):centerText)+'</text><text x="100" y="103" text-anchor="middle" class="ring-caption">'+escapeText(caption)+'</text>'; }svg+='</svg>';const legend='<div class="ring-legend">'+segments.map(s=>'<div><i style="background:'+s.color+'"></i><span>'+escapeText(s.label)+'<br><b>'+s.value.toLocaleString('pt-BR',{maximumFractionDigits:1})+(total?' · '+percent(100*s.value/total):'')+'</b></span></div>').join('')+'</div>';$(target).innerHTML=svg+legend;}
function renderOverview(){const online=cameras.filter(c=>c.status==='online').length,offline=cameras.filter(c=>c.status==='offline').length,unknown=cameras.length-online-offline-cameras.filter(c=>c.is_free).length;$('operation-count').textContent=online;$('registered-count').textContent=cameras.length;$('attention-count').textContent=alertData?alertData.summary.open:'—';ring('current-status-chart',[{label:'Online',value:online,color:'#21965a'},{label:'Offline',value:offline,color:'#d32e3a'},{label:'Não verificada',value:unknown,color:'#9ba99f'},{label:'Canal livre',value:cameras.filter(c=>c.is_free).length,color:'#6e8296'}],'câmeras');ring('makers-chart',[{label:'Intelbras',value:cameras.filter(c=>c.manufacturer==='Intelbras').length,color:'#194b35'},{label:'Hikvision',value:cameras.filter(c=>c.manufacturer==='Hikvision').length,color:'#67a287'}],'Fabricantes',true);if(overviewData){$('live-count').textContent=overviewData.live_views;$('users-count').textContent=overviewData.registered_users;$('online-users-count').textContent=overviewData.online_users;$('web-users-count').textContent=overviewData.online_users;$('changes-count').textContent=overviewData.status_changes_24h;$('failures-count').textContent=overviewData.offline_changes_24h;ring('types-chart',[{label:'Canal de gravador',value:overviewData.device_types.nvr,color:'#194b35'},{label:'Câmera direta',value:overviewData.device_types.camera,color:'#67a287'},{label:'Sem configuração',value:overviewData.device_types.unknown,color:'#9ba99f'}],'Tipos de acesso',true);ring('offline-age-chart',[{label:'Menos de 72h',value:overviewData.offline_recent,color:'#e0444e'},{label:'72h ou mais',value:overviewData.offline_old,color:'#9f1d2c'},{label:'Início desconhecido',value:overviewData.offline_unknown,color:'#9ba99f'}],'offline');}else{$('types-chart').innerHTML='<span class="muted">Aguardando dados…</span>';$('offline-age-chart').innerHTML='<span class="muted">Aguardando dados…</span>';}if(reportData&&reportData.camera_count){ring('coverage-chart',[{label:'Verificado',value:reportData.coverage,color:'#21965a'},{label:'Sem dados',value:Math.max(0,100-reportData.coverage),color:'#9ba99f'}],'cobertura',false,percent(reportData.coverage));}else{$('coverage-chart').innerHTML='<span class="muted">Selecione o período para consultar.</span>';}}

const alertKinds={offline:'Conexão indisponível',unverified:'Sem verificação válida'},alertStates={open:'Aberto',acknowledged:'Reconhecido',resolved:'Resolvido'};
async function loadAlerts(snap=null,redraw=true){const result=snap?snap.alerts:await api('/alerts?state_filter='+$('alert-filter').value);alertData=result;maintenanceData=snap?snap.maintenance:await api('/maintenance');if(redraw)render();$('alert-dashboard-detail').textContent=result.summary.acknowledged+' reconhecidos · '+result.summary.maintenance+' em manutenção · '+result.summary.recurring_devices+' recorrentes (30d)';$('alert-stats').innerHTML=[['Ativos',result.summary.open],['Reconhecidos',result.summary.acknowledged],['Em manutenção',result.summary.maintenance]].map(x=>'<div class="stat">'+x[0]+'<b>'+x[1]+'</b></div>').join('');$('alert-table').innerHTML=result.rows.map(a=>'<tr><td>'+escapeText(a.name)+'<small>'+alertKinds[a.kind]+'</small></td><td>'+alertStates[a.state]+'<small>'+escapeText(a.resolution||'')+'</small></td><td>'+new Date(a.opened_at*1000).toLocaleString('pt-BR')+'<small>'+duration((a.resolved_at||Date.now()/1000)-a.opened_at)+'</small></td><td>'+escapeText(a.owner||'Não atribuído')+'</td><td><button data-alert="'+a.id+'">'+(a.state==='resolved'?'Detalhes':'Tratar')+'</button></td></tr>').join('')||'<tr><td colspan="5">Nenhum alerta neste filtro.</td></tr>';$('maintenance-list').innerHTML=maintenanceData.map(m=>'<div class="maintenance-row"><span><b>'+escapeText((cameras.find(c=>c.id===m.camera_id)||{}).name||'Dispositivo')+'</b><small>Até '+new Date(m.until*1000).toLocaleString('pt-BR')+' · '+escapeText(m.reason)+'</small></span><button data-maintenance="'+m.camera_id+'">Gerenciar</button></div>').join('')||'<p class="muted">Nenhuma manutenção ativa. Programe na aba Dispositivos.</p>';renderOverview();}
async function alertForm(id){activeAlert=alertData.rows.find(a=>a.id===id);if(!activeAlert)return;try{const users=await api('/alert-operators');$('alert-owner').innerHTML='<option value="">Não atribuído</option>'+users.map(u=>'<option>'+escapeText(u)+'</option>').join('');$('alert-owner').value=activeAlert.owner;$('alert-ack').checked=activeAlert.state==='acknowledged';$('alert-note').value='';$('alert-description').textContent=activeAlert.name+' · '+alertKinds[activeAlert.kind]+' · '+alertStates[activeAlert.state];$('alert-notes').innerHTML=activeAlert.notes.map(n=>'<p><b>'+escapeText(n.username)+'</b> · '+new Date(n.timestamp*1000).toLocaleString('pt-BR')+'<br>'+escapeText(n.text)+'</p>').join('')||'<p>Sem observações.</p>';$('alert-form-error').textContent='';$('alert-form').querySelector('button.primary').hidden=activeAlert.state==='resolved';$('alert-dialog').showModal();}catch(e){toast(e.message);}}
$('alert-form').onsubmit=async e=>{e.preventDefault();try{await api('/alerts/'+activeAlert.id+'/treat',{method:'POST',body:JSON.stringify({owner:$('alert-owner').value,acknowledge:$('alert-ack').checked,note:$('alert-note').value})});$('alert-dialog').close();await loadAlerts();toast('Tratamento registrado.');}catch(e){$('alert-form-error').textContent=e.message;}};
function maintenanceForm(id){maintenanceCamera=id;const c=cameras.find(c=>c.id===id);if(!c)return;$('maintenance-device').textContent=c.name;const m=maintenanceData.find(m=>m.camera_id===id);$('maintenance-reason').value=m?m.reason:'';$('maintenance-minutes').value=m?'0':'60';$('maintenance-error').textContent='';$('maintenance-dialog').showModal();}
$('maintenance-form').onsubmit=async e=>{e.preventDefault();try{await api('/cameras/'+maintenanceCamera+'/maintenance',{method:'POST',body:JSON.stringify({minutes:Number($('maintenance-minutes').value),reason:$('maintenance-reason').value})});$('maintenance-dialog').close();await loadAlerts();toast('Manutenção atualizada.');}catch(e){$('maintenance-error').textContent=e.message;}};
$('alert-filter').onchange=()=>loadAlerts().catch(e=>toast(e.message));$('alert-cancel').onclick=()=>$('alert-dialog').close();$('maintenance-cancel').onclick=()=>$('maintenance-dialog').close();

// Organization, source filters and previewed bulk registration.
function optionList(rows,label='name'){return rows.map(r=>'<option value="'+r.id+'">'+escapeText(r[label])+'</option>').join('');}
function setOptions(id,html){const el=$(id),previous=el.value;el.innerHTML=html;if([...el.options].some(o=>o.value===previous))el.value=previous;}
function recorderKey(c){return [c.unit_id,c.ip,c.port].join('|');}
function updateInventoryFilters(){setOptions('filter-unit','<option value="">Todas</option>'+optionList(units));setOptions('scope-unit','<option value="">Todas as unidades</option>'+optionList(units));$('scope-unit').value=$('filter-unit').value;const uid=Number($('filter-unit').value);setOptions('filter-sector','<option value="">Todos</option>'+optionList(sectors.filter(s=>!uid||s.unit_ids.includes(uid))));const recorders=new Map();cameras.filter(c=>c.device_type==='nvr'&&(!uid||c.unit_id===uid)).forEach(c=>{const key=recorderKey(c);if(!recorders.has(key))recorders.set(key,(c.recorder_name||c.ip)+' · '+c.ip+':'+c.port+' · '+c.unit_name);});setOptions('filter-recorder','<option value="">Todos</option>'+[...recorders].map(([key,label])=>'<option value="'+escapeText(key)+'">'+escapeText(label)+'</option>').join(''));$('current-unit-name').textContent=(units.find(u=>u.id===uid)||{}).name||'Todas as unidades';}
function setFormUnits(prefix,value){$(prefix+'-unit').innerHTML=optionList(units);$(prefix+'-unit').value=String(value||units[0]?.id||1);setFormSectors(prefix,0);}
function setFormSectors(prefix,value=0){const uid=Number($(prefix+'-unit').value);$(prefix+'-sector').innerHTML='<option value="0">Sem setor</option>'+optionList(sectors.filter(s=>s.unit_ids.includes(uid)));$(prefix+'-sector').value=String(value);if(!$(prefix+'-sector').value)$(prefix+'-sector').value='0';}
function setDeviceOrganization(c){setFormUnits('device',c.unit_id);setFormSectors('device',c.sector_id);if(!c.id){const u=units.find(u=>u.id===c.unit_id);if(u){c.lat=u.lat;c.lng=u.lng;}}}
function changedDeviceUnit(){setFormSectors('device');const u=units.find(u=>u.id===Number($('device-unit').value));if(u&&!editing){$('device-form').elements.lat.value=u.lat;$('device-form').elements.lng.value=u.lng;}}
function channelsFrom(text){const result=[];for(const chunk of text.split(',')){const part=chunk.trim();if(!/^\d+(\s*-\s*\d+)?$/.test(part))throw Error('Use canais como 1-16 ou 1,3,5-8.');const [first,last]=part.split('-').map(Number);if(first<1||first>256||(last!==undefined&&(last<first||last>256)))throw Error('Informe canais entre 1 e 256, em ordem crescente nos intervalos.');for(let n=first;n<=(last===undefined?first:last);n++)result.push(n);}if(new Set(result).size!==result.length)throw Error('Há canais repetidos na seleção.');if(result.length>256)throw Error('Limite de 256 canais por gravador.');return result;}
function invalidatePreview(kind){if(kind==='batch'){batchToken=null;batchGeneration++;}else{importToken=null;importGeneration++;}$(kind+'-commit').disabled=true;$(kind+'-preview').innerHTML='';}
function showPreview(kind,result){if(kind==='batch')batchToken=result.token;else importToken=result.token;$(kind+'-commit').disabled=!result.token;$(kind+'-preview').innerHTML='<p><b>'+result.valid+' válidos</b> · '+result.invalid+' com erro · '+result.total+' dispositivos'+(result.token?' · Prévia válida por 15 minutos':' · Corrija os erros e valide novamente')+'</p><div class="table-wrap"><table><thead><tr><th>Linha</th><th>Nome / gravador</th><th>IP / canal</th><th>Localização</th><th>Validação</th></tr></thead><tbody>'+result.rows.map(r=>'<tr><td>'+r.row+'</td><td>'+escapeText(r.name)+'<small>'+escapeText(r.recorder_name)+'</small></td><td>'+escapeText(r.ip)+'<small>Canal '+escapeText(r.channel)+'</small></td><td>'+escapeText((units.find(u=>u.id===r.unit_id)||{}).name||'—')+'<small>'+escapeText((sectors.find(s=>s.id===r.sector_id)||{}).name||'Sem setor')+'</small></td><td class="'+(r.errors.length?'workflow-error':'preview-ok')+'">'+(r.errors.length?r.errors.map(escapeText).join('<br>'):(r.is_free?'Canal livre — desativado':'Pronto para cadastrar'))+'</td></tr>').join('')+'</tbody></table></div>';}
function openBatch(){const f=$('batch-form');f.reset();invalidatePreview('batch');setFormUnits('batch',Number($('filter-unit').value)||1);const u=units.find(u=>u.id===Number($('batch-unit').value));f.elements.lat.value=u?.lat||0;f.elements.lng.value=u?.lng||0;$('batch-error').textContent='';$('batch-channel-flags').innerHTML='';buildChannelFlags();$('batch-dialog').showModal();}
function openImport(){$('import-form').reset();invalidatePreview('import');setFormUnits('import',Number($('filter-unit').value)||1);$('import-error').textContent='';$('import-dialog').showModal();}
async function validateBatch(e){e.preventDefault();invalidatePreview('batch');const generation=batchGeneration;const f=$('batch-form'),body=Object.fromEntries(new FormData(f));$('batch-error').textContent='Validando canais…';$('batch-validate').disabled=true;try{const channels=channelsFrom(body.channels);for(const key of ['unit_id','sector_id','port','lat','lng'])body[key]=Number(body[key]);const prefix=body.prefix;delete body.prefix;delete body.channels;const result=await api('/inventory/batch-preview',{method:'POST',body:JSON.stringify({device:body,channels,prefix,free_channels:[...$('batch-channel-flags').querySelectorAll('input:checked')].map(el=>Number(el.dataset.channel))})});if(generation!==batchGeneration)return;showPreview('batch',result);$('batch-error').textContent='';}catch(error){if(generation===batchGeneration)$('batch-error').textContent=error.message;}finally{$('batch-validate').disabled=false;}}
async function validateImport(e){e.preventDefault();invalidatePreview('import');const generation=importGeneration;const file=$('import-file').files[0];$('import-error').textContent='Validando arquivo…';$('import-validate').disabled=true;try{if(!file||file.size>2000000)throw Error('Selecione um arquivo CSV ou Excel de até 2 MB.');const format=file.name.toLowerCase().split('.').pop();if(!['csv','xlsx'].includes(format))throw Error('Use CSV ou Excel .xlsx.');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));const defaults=Object.fromEntries(new FormData($('import-form')));defaults.unit_id=Number(defaults.unit_id);defaults.sector_id=Number(defaults.sector_id);const result=await api('/inventory/import-preview',{method:'POST',body:JSON.stringify({format,content:btoa(binary),defaults})});if(generation!==importGeneration)return;showPreview('import',result);$('import-error').textContent='';}catch(error){if(generation===importGeneration)$('import-error').textContent=error.message;}finally{$('import-validate').disabled=false;}}
async function commitInventory(kind){const token=kind==='batch'?batchToken:importToken;if(!token)return;$(kind+'-commit').disabled=true;$(kind+'-validate').disabled=true;const form=$(kind+'-form');const fields=[...form.querySelectorAll('input,select')];fields.forEach(el=>el.disabled=true);try{const result=await api('/inventory/commit',{method:'POST',body:JSON.stringify({token})});form.elements.password.value='';$(kind+'-dialog').close();invalidatePreview(kind);devicePage=1;await load();toast(result.created+' dispositivos cadastrados.');}catch(error){$(kind+'-error').textContent=error.message;if(kind==='batch')batchToken=null;else importToken=null;$(kind+'-commit').disabled=true;}finally{fields.forEach(el=>el.disabled=false);$(kind+'-validate').disabled=false;}}
async function downloadTemplate(format){try{const response=await fetch('/api/inventory/template/'+format,{headers:{Authorization:'Bearer '+authToken}});if(!response.ok)throw Error('Não foi possível baixar o modelo. Verifique o login.');const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download='modelo-dispositivos.'+format;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){toast(e.message);}}
function renderOrganization(){const previous=$('organization-unit').value;$('organization-unit').innerHTML=optionList(units);if(units.some(u=>String(u.id)===previous))$('organization-unit').value=previous;$('link-sector-select').innerHTML=optionList(sectors);$('organization-list').innerHTML='<h3>Unidades e setores vinculados</h3>'+ (units.map(u=>{const list=sectors.filter(x=>x.unit_ids.includes(u.id));const count=cameras.filter(c=>c.unit_id===u.id).length;return '<div class="organization-item"><div class="actions"><b>'+escapeText(u.name)+'</b><button type="button" data-location-unit="'+u.id+'">Editar localização</button><button class="danger" type="button" data-delete-unit="'+u.id+'">Excluir unidade</button></div><small>'+count+' dispositivos · '+list.length+' setores</small><div>'+list.map(x=>'<div class="organization-sector-row"><span>'+escapeText(x.name)+'</span><button type="button" data-unlink-unit="'+u.id+'" data-unlink-sector="'+x.id+'">Desvincular</button></div>').join('')+'</div>'+(list.length?'':'<p>Sem setores vinculados.</p>')+'</div>';}).join('')||'<p>Nenhuma unidade cadastrada.</p>')+'<h3>Catálogo global de setores</h3>'+sectors.map(x=>'<div class="organization-sector-row"><span>'+escapeText(x.name)+' <small>'+x.unit_ids.length+' unidades vinculadas</small></span><button type="button" class="danger" data-delete-sector="'+x.id+'">Excluir setor global</button></div>').join('');}

async function reloadOrganization(){[units,sectors]=await Promise.all([api('/units'),api('/sectors')]);renderOrganization();for(const prefix of ['device','batch','import']){const uid=$(prefix+'-unit').value,sid=$(prefix+'-sector').value;setFormUnits(prefix,uid);setFormSectors(prefix,Number(sid));}if(positionCameraId){const c=cameras.find(c=>c.id===positionCameraId);const previous=$('position-sector').value;$('position-sector').innerHTML='<option value="0">Sem setor</option>'+optionList(sectors.filter(s=>s.unit_ids.includes(c?.unit_id)));$('position-sector').value=previous||'0';}render();}
$('open-batch').onclick=openBatch;$('open-import').onclick=openImport;$('batch-form').onsubmit=validateBatch;$('import-form').onsubmit=validateImport;$('batch-commit').onclick=()=>commitInventory('batch');$('import-commit').onclick=()=>commitInventory('import');
['batch','import'].forEach(kind=>{['input','change'].forEach(event=>$(kind+'-form').addEventListener(event,()=>invalidatePreview(kind)));$(kind+'-dialog').addEventListener('close',()=>{$(kind+'-form').elements.password.value='';invalidatePreview(kind);});$(kind+'-unit').onchange=()=>{setFormSectors(kind);if(kind==='batch'){const u=units.find(u=>u.id===Number($('batch-unit').value));if(u){$('batch-form').elements.lat.value=u.lat;$('batch-form').elements.lng.value=u.lng;}}};});
$('device-unit').onchange=changedDeviceUnit;
['filter-unit','filter-sector','filter-recorder','filter-manufacturer','filter-status','filter-maintenance'].forEach(id=>$(id).onchange=()=>{devicePage=1;render();});$('scope-unit').onchange=()=>{$('filter-unit').value=$('scope-unit').value;devicePage=1;render();};$('clear-inventory-filters').onclick=()=>{['filter-unit','filter-sector','filter-recorder','filter-manufacturer','filter-status','filter-maintenance'].forEach(id=>$(id).value='');$('search').value='';$('only-online').checked=false;devicePage=1;render();};$('device-prev').onclick=()=>{devicePage--;render();};$('device-next').onclick=()=>{devicePage++;render();};
$('manage-organization').onclick=()=>{renderOrganization();$('organization-error').textContent='';page('organization');};
$('unit-form').onsubmit=async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.target));body.lat=Number(body.lat);body.lng=Number(body.lng);try{await api('/units',{method:'POST',body:JSON.stringify(body)});e.target.reset();await reloadOrganization();$('organization-error').textContent='';toast('Unidade cadastrada.');}catch(error){$('organization-error').textContent=error.message;}};
$('sector-form').onsubmit=async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.target));body.unit_id=0;try{await api('/sectors',{method:'POST',body:JSON.stringify(body)});e.target.elements.name.value='';await reloadOrganization();$('organization-error').textContent='';toast('Setor cadastrado.');}catch(error){$('organization-error').textContent=error.message;}};
document.addEventListener('click',e=>{const button=e.target.closest('button');if(!button)return;if(button.dataset.closeDialog)$(button.dataset.closeDialog).close();if(button.dataset.template)downloadTemplate(button.dataset.template);});

function buildChannelFlags(){const previous=new Set([...$('batch-channel-flags').querySelectorAll('input:checked')].map(el=>Number(el.dataset.channel)));try{const channels=channelsFrom($('batch-form').elements.channels.value);$('batch-channel-flags').innerHTML=channels.map(ch=>'<label><input type="checkbox" data-channel="'+ch+'" '+(previous.has(ch)?'checked':'')+'> Canal '+String(ch).padStart(2,'0')+' livre</label>').join('');}catch(e){$('batch-channel-flags').innerHTML='<p class="muted">Informe uma seleção válida de canais acima.</p>';}}
$('batch-form').elements.channels.addEventListener('input',buildChannelFlags);
document.addEventListener('change',async e=>{const el=e.target;if(!el.dataset.freeChannel)return;el.disabled=true;try{await api('/cameras/'+el.dataset.freeChannel+'/channel-mode',{method:'PATCH',body:JSON.stringify({is_free:el.checked})});await load();toast(el.checked?'Canal livre: monitoramento desativado.':'Canal reativado. Aguardando verificação.');}catch(error){el.checked=!el.checked;toast(error.message);}finally{el.disabled=false;}});

function setBasemap(name){if(!map||!basemaps[name])return;$('satellite-detail-control').hidden=name!=='satellite';if(activeBasemap)map.removeLayer(activeBasemap);activeBasemap=basemaps[name];activeBasemap.addTo(map);$('map-basemap').value=name;$('map-imagery-status').textContent=name==='satellite'?'Satélite · zoom amplia a imagem disponível; detalhe superior depende de cobertura':'Mapa de ruas · depende de internet';try{localStorage.setItem('scheffer-basemap',name);}catch{}clearTimeout(basemapTimer);basemapTimer=setTimeout(()=>{if(!activeBasemap.schefferLoaded)$('map-imagery-status').textContent='Imagens indisponíveis. Verifique internet ou alterne a camada.';},8000);}
function refreshPositionCameraOptions(){const previous=String(positionCameraId||'');$('position-camera').innerHTML='<option value="">Selecione uma câmera</option>'+filtered().map(c=>'<option value="'+c.id+'">'+escapeText(c.name)+(c.sector_name?' · '+escapeText(c.sector_name):'')+'</option>').join('');if([...$('position-camera').options].some(o=>o.value===previous))$('position-camera').value=previous;else if(positionCameraId&&!positionSaving){positionCameraId=null;if(draftMarker){map.removeLayer(draftMarker);draftMarker=null;}$('position-sector').innerHTML='';$('position-message').textContent='Câmera fora do filtro. Selecione outra câmera.';}}
function openPositioning(){if(!map){toast('Mapa indisponível. Verifique o carregamento do Leaflet.');return;}stopLive();$('viewer').hidden=true;positioning=true;$('position-panel').hidden=false;$('position-message').textContent='As coordenadas só serão gravadas ao clicar em Salvar posição.';refreshPositionCameraOptions();if(selected&&filtered().some(c=>c.id===selected))choosePositionCamera(selected);}
function closePositioning(){if(positionSaving)return;positioning=false;positionCameraId=null;$('position-panel').hidden=true;if(draftMarker){map.removeLayer(draftMarker);draftMarker=null;}}
function choosePositionCamera(id){if(positionSaving)return;const c=cameras.find(c=>c.id===Number(id));if(!c)return;positionCameraId=c.id;$('position-camera').value=String(c.id);$('position-unit').textContent=c.unit_name+' · '+names[c.status];$('position-sector').innerHTML='<option value="0">Sem setor</option>'+optionList(sectors.filter(s=>s.unit_ids.includes(c.unit_id)));$('position-sector').value=String(c.sector_id);$('position-message').textContent='Clique no mapa ou arraste o balão azul. Nada foi salvo ainda.';setDraftPosition(c.lat,c.lng);map.panTo([c.lat,c.lng]);}
function setDraftPosition(lat,lng){if(!Number.isFinite(lat)||!Number.isFinite(lng)||lat<-90||lat>90||lng<-180||lng>180){$('position-message').textContent='Coordenadas inválidas.';return;}$('position-lat').value=lat.toFixed(7);$('position-lng').value=lng.toFixed(7);if(draftMarker)draftMarker.setLatLng([lat,lng]);else{draftMarker=L.marker([lat,lng],{draggable:true,zIndexOffset:2000,icon:L.divIcon({className:'pin-wrap',html:'<div class="pin draft-pin"><span>✥</span></div>',iconSize:[40,44],iconAnchor:[20,44]})}).addTo(map);draftMarker.on('dragend',()=>{const p=draftMarker.getLatLng();setDraftPosition(p.lat,p.lng);});}draftMarker.bindTooltip('Nova posição · '+escapeText(cameras.find(c=>c.id===positionCameraId)?.name||''),{permanent:true,direction:'top',offset:[0,-35]});}
async function saveCameraPosition(){if(!positionCameraId||positionSaving){$('position-message').textContent='Selecione uma câmera.';return;}const lat=Number($('position-lat').value),lng=Number($('position-lng').value);if(!$('position-lat').value||!$('position-lng').value||!Number.isFinite(lat)||!Number.isFinite(lng)||lat<-90||lat>90||lng<-180||lng>180){$('position-message').textContent='Informe coordenadas válidas.';return;}positionSaving=true;$('position-save').disabled=true;$('position-camera').disabled=true;$('position-sector').disabled=true;$('position-close').disabled=true;$('position-lat').disabled=true;$('position-lng').disabled=true;if(draftMarker)draftMarker.dragging.disable();try{const saved=await api('/cameras/'+positionCameraId+'/position',{method:'PATCH',body:JSON.stringify({lat,lng,sector_id:Number($('position-sector').value)})});cameras=cameras.map(c=>c.id===saved.id?saved:c);render();$('position-message').textContent='Posição e setor salvos. Selecione a próxima câmera.';toast('Posição salva para '+saved.name+'.');}catch(e){$('position-message').textContent=e.message;}finally{positionSaving=false;$('position-save').disabled=false;$('position-camera').disabled=false;$('position-sector').disabled=false;$('position-close').disabled=false;$('position-lat').disabled=false;$('position-lng').disabled=false;if(draftMarker)draftMarker.dragging.enable();}}
$('map-basemap').onchange=()=>setBasemap($('map-basemap').value);$('map-labels').onchange=render;$('position-cameras').onclick=openPositioning;$('position-close').onclick=closePositioning;$('position-camera').onchange=()=>{if($('position-camera').value)choosePositionCamera(Number($('position-camera').value));else{positionCameraId=null;if(draftMarker){map.removeLayer(draftMarker);draftMarker=null;}}};$('position-save').onclick=saveCameraPosition;$('position-recenter').onclick=()=>{if(map&&draftMarker)map.setView(draftMarker.getLatLng(),Math.max(map.getZoom(),18));};['position-lat','position-lng'].forEach(id=>$(id).onchange=()=>{if(positionCameraId&&!positionSaving)setDraftPosition(Number($('position-lat').value),Number($('position-lng').value));});

function setSatelliteDetail(value){const detail=Number(value);if(![16,17,18,19].includes(detail)||!basemaps.satellite)return;const old=basemaps.satellite;const wasActive=activeBasemap===old;if(wasActive)map.removeLayer(old);const layer=L.tileLayer('https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxNativeZoom:detail,maxZoom:21,attribution:'Tiles © Esri — Source: Esri, Maxar, Earthstar Geographics, and the GIS User Community'});layer.on('tileload',()=>{if(layer===activeBasemap){layer.schefferLoaded=true;$('map-fallback').hidden=true;clearTimeout(basemapTimer);}});layer.on('tileerror',()=>{if(layer===activeBasemap)$('map-imagery-status').textContent='Falha ao carregar imagens. Use Detalhe Compatível (16) ou alterne para Ruas.';});basemaps.satellite=layer;if(wasActive){activeBasemap=layer;layer.addTo(map);}$('map-imagery-status').textContent='Detalhe satélite '+detail+'. Se aparecer "Map data not yet available", escolha Compatível (16).';}
$('satellite-detail').onchange=()=>setSatelliteDetail($('satellite-detail').value);

function cameraPinIcon(status,count=null){const isGroup=count!==null;const color=isGroup?'#287ac0':({online:'#1c974c',offline:'#d63b45',unknown:'#83948a',free:'#6e8296'}[status]||'#83948a');const center=isGroup?'<text x="20" y="25" text-anchor="middle" fill="#23466b" font-family="Segoe UI,Arial,sans-serif" font-size="'+(count>99?13:18)+'" font-weight="700">'+count+'</text>':'<path d="M12 15h11v10H12z M23 18l6-4v12l-6-4z" fill="#16372b"/>';return L.divIcon({className:'camera-location-pin',html:'<svg width="30" height="39" viewBox="0 0 40 52" aria-hidden="true"><path d="M20 51C18 42 3 31 3 20A17 17 0 1 1 37 20C37 31 22 42 20 51Z" fill="'+color+'" stroke="white" stroke-width="1.5"/><circle cx="20" cy="20" r="12.5" fill="white"/>'+center+'</svg>',iconSize:[30,39],iconAnchor:[15,38.25],tooltipAnchor:[0,-35.25]});}
function renderMapGroups(visible){visible=visible.filter(c=>!c.is_free);if(!map||!markers)return;const signature=JSON.stringify([map.getZoom(),expandedCameraGroup,$('map-labels').checked,visible.map(c=>[c.id,c.lat,c.lng,c.status,c.name,c.sector_name])]);if(signature===lastMapSignature)return;lastMapSignature=signature;markers.clearLayers();const zoom=map.getZoom(),projected=visible.map(c=>{const p=map.project([c.lat,c.lng],zoom);return {x:p.x,y:p.y,camera:c};});const groups=groupCameraPoints(projected,58);groups.forEach(group=>{if(group.length===1){addCameraMapPin(group[0].camera,[group[0].camera.lat,group[0].camera.lng]);return;}const key=group.map(p=>p.camera.id).sort((a,b)=>a-b).join(',');const centerPoint=L.point(group.reduce((sum,p)=>sum+p.x,0)/group.length,group.reduce((sum,p)=>sum+p.y,0)/group.length);const center=map.unproject(centerPoint,zoom);if(expandedCameraGroup===key){const count=group.length;group.forEach((p,i)=>{const angle=2*Math.PI*i/count-Math.PI/2;const radius=Math.max(65,count*22/(2*Math.PI));const display=map.unproject(L.point(centerPoint.x+Math.cos(angle)*radius,centerPoint.y+Math.sin(angle)*radius),zoom);L.polyline([[p.camera.lat,p.camera.lng],display],{color:'#577b99',weight:1.5,opacity:.65,interactive:false}).addTo(markers);addCameraMapPin(p.camera,display,true);});return;}const marker=L.marker(center,{icon:cameraPinIcon(null,group.length),title:group.length+' câmeras neste grupo',keyboard:true}).bindTooltip(group.length+' câmeras · clique para aproximar',{direction:'top',className:'camera-map-label'}).on('click',()=>{if(map.getZoom()>=21){expandedCameraGroup=key;renderMapGroups(filtered());}else{map.fitBounds(L.latLngBounds(group.map(p=>[p.camera.lat,p.camera.lng])),{padding:[65,65],maxZoom:Math.min(21,map.getZoom()+3)});}});marker.addTo(markers);});}
function addCameraMapPin(c,point,spread=false){const title=c.name+(c.sector_name?' · '+c.sector_name:'');L.marker(point,{icon:cameraPinIcon(c.status),title:title+' · '+names[c.status]}).bindTooltip(escapeText(title)+(spread?' · posição visual expandida':''),{permanent:$('map-labels').checked,direction:'top',className:'camera-map-label'}).on('click',()=>{if(positioning)choosePositionCamera(c.id);else openCamera(c.id);}).addTo(markers);}

$('organization-menu').onclick=()=>$('manage-organization').click();

$('organization-list').addEventListener('click',async e=>{const button=e.target.closest('button');if(!button)return;const sectorId=button.dataset.deleteSector,unitId=button.dataset.deleteUnit;if(!sectorId&&!unitId)return;const item=sectorId?sectors.find(x=>x.id===Number(sectorId)):units.find(x=>x.id===Number(unitId));if(!item||!confirm('Excluir '+(sectorId?'o setor ':'a unidade ')+item.name+'?'))return;button.disabled=true;try{await api((sectorId?'/sectors/':'/units/')+(sectorId||unitId),{method:'DELETE'});await reloadOrganization();$('organization-error').textContent='';toast('Cadastro excluído.');}catch(error){$('organization-error').textContent=error.message;button.disabled=false;}});

$('link-sector-form').onsubmit=async e=>{e.preventDefault();const uid=$('organization-unit').value,sid=$('link-sector-select').value;if(!uid||!sid){$('organization-error').textContent='Cadastre e selecione uma unidade e um setor.';return;}try{await api('/units/'+uid+'/sectors/'+sid,{method:'PUT'});await reloadOrganization();$('organization-error').textContent='';toast('Setor vinculado à unidade.');}catch(error){$('organization-error').textContent=error.message;}};
$('organization-list').addEventListener('click',async e=>{const b=e.target.closest('[data-unlink-sector]');if(!b)return;if(!confirm('Desvincular este setor apenas desta unidade?'))return;b.disabled=true;try{await api('/units/'+b.dataset.unlinkUnit+'/sectors/'+b.dataset.unlinkSector,{method:'DELETE'});await reloadOrganization();$('organization-error').textContent='';}catch(error){$('organization-error').textContent=error.message;b.disabled=false;}});

function updateDeviceSelection(visible=filtered()){
 const allowed=new Set(visible.map(c=>c.id));
 for(const id of deviceSelection)if(!allowed.has(id))deviceSelection.delete(id);
 // Checkboxes were rendered before pruning; synchronize their current state.
 $('device-table').querySelectorAll('[data-select-device]').forEach(el=>el.checked=deviceSelection.has(Number(el.dataset.selectDevice)));
 $('device-selection-count').textContent=deviceSelection.size+' selecionadas';
 $('bulk-remove-devices').disabled=bulkRemoving||!deviceSelection.size;
 $('select-filtered-devices').disabled=bulkRemoving||!visible.length;
 $('clear-device-selection').disabled=bulkRemoving||!deviceSelection.size;
 const rows=visible.slice((devicePage-1)*50,devicePage*50);
 $('select-device-page').checked=!!rows.length&&rows.every(c=>deviceSelection.has(c.id));
 $('select-device-page').indeterminate=rows.some(c=>deviceSelection.has(c.id))&&!$('select-device-page').checked;
 $('select-device-page').disabled=bulkRemoving||!rows.length;
}
$('device-table').addEventListener('change',e=>{if(bulkRemoving||!e.target.matches('[data-select-device]'))return;const id=Number(e.target.dataset.selectDevice);if(e.target.checked)deviceSelection.add(id);else deviceSelection.delete(id);updateDeviceSelection();});
$('select-device-page').onchange=e=>{if(bulkRemoving)return;filtered().slice((devicePage-1)*50,devicePage*50).forEach(c=>e.target.checked?deviceSelection.add(c.id):deviceSelection.delete(c.id));render();};
$('select-filtered-devices').onclick=()=>{if(bulkRemoving)return;deviceSelection=new Set(filtered().map(c=>c.id));render();};
$('clear-device-selection').onclick=()=>{if(bulkRemoving)return;deviceSelection.clear();render();};
async function removeSelectedDevices(){
 if(bulkRemoving)return;
 const items=filtered().filter(c=>deviceSelection.has(c.id));if(!items.length)return;
 const summary=items.slice(0,10).map(c=>'• '+c.name).join('\n')+(items.length>10?'\n… e mais '+(items.length-10):'');
 if(!confirm('Excluir '+items.length+' dispositivos selecionados?\n\n'+summary+'\n\nOs cadastros e credenciais serão excluídos e cada remoção será registrada na auditoria. Esta ação não pode ser desfeita.'))return;
 bulkRemoving=true;render();$('bulk-remove-result').textContent='Iniciando remoção…';
 let removed=0,pendingGateway=0;const errors=[];
 try{
  for(let i=0;i<items.length;i++){
   const c=items[i];$('bulk-remove-result').textContent='Removendo '+(i+1)+' de '+items.length+'…';
   try{const result=await api('/cameras/'+c.id,{method:'DELETE'});removed++;if(!result.gateway_cleaned)pendingGateway++;deviceSelection.delete(c.id);cameras=cameras.filter(x=>x.id!==c.id);
    if(selected===c.id){stopLive();$('viewer').hidden=true;selected=null;}
    if(editing===c.id){$('device-form').elements.password.value='';$('device-dialog').close();editing=null;}
    if(positionCameraId===c.id)closePositioning();
   }catch(error){errors.push(c.name+': '+error.message);if(!authToken)break;}
  }
 }finally{bulkRemoving=false;await load();render();}
 const remaining=items.length-removed;
 $('bulk-remove-result').textContent=removed+' dispositivos removidos.'+(remaining?' '+remaining+' não removidos.':'')+(pendingGateway?' Limpeza de '+pendingGateway+' streams pendente; reinicie o serviço video.':'')+(errors.length?' '+errors.slice(0,5).join(' | '):'');
 toast(removed+' dispositivos removidos'+(remaining?' · '+remaining+' não removidos':''));
}
$('bulk-remove-devices').onclick=removeSelectedDevices;

let batchDiscoveryFingerprint=null,batchDiscoveryResult=null,batchDetecting=false;
function batchDiscoveryInput(){const f=$('batch-form').elements;const input={manufacturer:f.manufacturer.value,ip:f.ip.value.trim(),username:f.username.value,password:f.password.value,channels:channelsFrom(f.channels.value),management_port:Number($('batch-management-port').value),management_scheme:$('batch-management-scheme').value};if(!input.ip||!input.username||!input.password)throw Error('Preencha IP, usuário e senha do gravador.');if(!Number.isInteger(input.management_port)||input.management_port<1||input.management_port>65535)throw Error('Informe a porta web entre 1 e 65535.');return input;}
async function detectBatchChannels(){
 if(batchDetecting)throw Error('Aguarde a consulta em andamento.');
 const input=batchDiscoveryInput(),fingerprint=JSON.stringify(input);
 if(batchDiscoveryFingerprint===fingerprint&&batchDiscoveryResult)return batchDiscoveryResult;
 invalidatePreview('batch');batchDetecting=true;$('batch-detect').disabled=true;$('batch-validate').disabled=true;$('batch-discovery-message').textContent='Consultando cadastro de câmeras no gravador…';$('batch-discovery-reviewed').checked=false;
 try{
  const result=await api('/inventory/discover-channels',{method:'POST',body:JSON.stringify(input)});
  if(!$('batch-dialog').open||JSON.stringify(batchDiscoveryInput())!==fingerprint)throw Error('Os dados mudaram durante a consulta. Detecte novamente.');
  buildChannelFlags();let changed=false;
  for(const row of result.rows){const box=$('batch-channel-flags').querySelector('[data-channel="'+row.channel+'"]');if(box&&row.state!=='unknown'){const next=row.state==='free';if(box.checked!==next){box.checked=next;changed=true;}}}
  if(changed)invalidatePreview('batch');
  batchDiscoveryFingerprint=fingerprint;batchDiscoveryResult=result;
  $('batch-discovery-message').textContent=result.message;
  const labels={free:'Canal livre',configured:'Câmera cadastrada',unknown:'Revisão manual'};
  $('batch-discovery-results').innerHTML='<table><thead><tr><th>Canal</th><th>Cadastro</th><th>Detalhe</th></tr></thead><tbody>'+result.rows.map(r=>'<tr><td>'+r.channel+'</td><td>'+escapeText(labels[r.state])+'</td><td>'+escapeText(r.reason)+'</td></tr>').join('')+'</tbody></table>';
  $('batch-discovery-review-label').hidden=!result.rows.some(r=>r.state==='unknown');
  return result;
 }finally{batchDetecting=false;$('batch-detect').disabled=false;$('batch-validate').disabled=false;}
}
$('batch-detect').onclick=async()=>{try{batchDiscoveryFingerprint=null;batchDiscoveryResult=null;await detectBatchChannels();$('batch-error').textContent='';}catch(e){$('batch-error').textContent=e.message;}};
const validateBatchWithDiscovery=validateBatch;
validateBatch=async function(e){e.preventDefault();if(batchDetecting)return;try{if($('batch-auto-detect').checked){const result=await detectBatchChannels();if(result.rows.some(r=>r.state==='unknown')&&!$('batch-discovery-reviewed').checked){invalidatePreview('batch');throw Error('Revise os canais inconclusivos e marque a confirmação de revisão manual antes de validar.');}}await validateBatchWithDiscovery(e);}catch(error){$('batch-error').textContent=error.message;}};
$('batch-form').onsubmit=validateBatch;
$('batch-dialog').addEventListener('close',()=>{batchDiscoveryFingerprint=null;batchDiscoveryResult=null;$('batch-discovery-results').innerHTML='';$('batch-discovery-message').textContent='';$('batch-discovery-review-label').hidden=true;$('batch-discovery-reviewed').checked=false;});

function unitLocationCount(){const f=$('unit-location-form'),u=units.find(x=>x.id===Number(f.elements.unit_id.value));if(!u)return 0;const scope=f.elements.camera_scope.value;return cameras.filter(c=>c.unit_id===u.id&&(scope==='all'||scope==='center'&&Math.abs(c.lat-u.lat)<=0.000001&&Math.abs(c.lng-u.lng)<=0.000001)).length;}
function showUnitLocationCount(){$('unit-location-count').textContent=unitLocationCount()+' câmeras terão a posição atualizada, incluindo canais livres que correspondam à opção escolhida.';}
$('organization-list').addEventListener('click',e=>{const b=e.target.closest('[data-location-unit]');if(!b)return;const u=units.find(x=>x.id===Number(b.dataset.locationUnit));if(!u)return;const f=$('unit-location-form');f.reset();f.elements.unit_id.value=u.id;f.elements.lat.value=u.lat;f.elements.lng.value=u.lng;$('unit-location-title').textContent='Editar localização — '+u.name;f.hidden=false;showUnitLocationCount();f.scrollIntoView({behavior:'smooth',block:'center'});});
$('unit-location-form').elements.camera_scope.onchange=showUnitLocationCount;
$('cancel-unit-location').onclick=()=>$('unit-location-form').hidden=true;
$('unit-location-form').onsubmit=async e=>{e.preventDefault();const f=e.target,id=Number(f.elements.unit_id.value),body={lat:Number(f.elements.lat.value),lng:Number(f.elements.lng.value),camera_scope:f.elements.camera_scope.value};if(!confirm('Salvar o centro da filial em '+body.lat+', '+body.lng+' e atualizar a posição de '+unitLocationCount()+' câmeras?'))return;const b=f.querySelector('[type="submit"]');b.disabled=true;try{const r=await api('/units/'+id+'/location',{method:'PATCH',body:JSON.stringify(body)});cameras=await api('/cameras');await reloadOrganization();f.hidden=true;$('organization-error').textContent='';toast('Localização salva. '+r.updated_cameras+' câmeras atualizadas.');}catch(error){$('organization-error').textContent=error.message;}finally{b.disabled=false;}};

function renderCameraDetails(c){const playing=liveReceivingId===c.id&&Date.now()-lastVideoProgress<5000;const indicator=c.status;$('viewer-title').textContent=c.name;$('viewer-status').innerHTML='<i class="dot '+(indicator==='online'?'online':indicator==='offline'?'offline':'unknown')+'"></i>';$('viewer-status').setAttribute('aria-label',playing?'Vídeo recebido agora · monitor: '+(names[c.status]||'Não verificada'):(names[c.status]||'Não verificada'));$('viewer-status').title=playing?'Vídeo recebido agora · monitor: '+(names[c.status]||'Não verificada'):(names[c.status]||'Não verificada');$('viewer-info').textContent='Unidade: '+(c.unit_name||'Unidade não informada');$('viewer-id').textContent='Id: '+c.id;$('viewer-details').innerHTML=[['Latitude',Number(c.lat).toFixed(11)],['Longitude',Number(c.lng).toFixed(11)],['Setor',c.sector_name||'Sem setor']].map(([label,value])=>'<div><dt>'+escapeText(label)+': </dt><dd>'+escapeText(String(value))+'</dd></div>').join('');$('viewer-checked').textContent='';$('viewer-diagnostic').textContent=c.diagnostic||'';}
$('retry-live').onclick=()=>{if(selected)startLive(selected);};

async function openReadyLive(id,generation){
 const canceled=()=>generation!==playGeneration;const deadline=Date.now()+45000;
 const request=async(path,options,timeout)=>{const controller=new AbortController();liveAbort=controller;const timer=setTimeout(()=>controller.abort(),timeout);try{return await fetch(path,{...options,signal:controller.signal,cache:'no-store'});}finally{clearTimeout(timer);if(liveAbort===controller)liveAbort=null;}};
 const ticket=async()=>{const r=await request('/api/cameras/'+id+'/live',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+authToken,'X-Video-Client':videoClientKey}},Math.max(1,Math.min(40000,deadline-Date.now())));const data=await r.json();if(!r.ok){const e=Error(data.detail||'Falha ao preparar vídeo.');e.status=r.status;throw e;}return data;};
 let result=await ticket();if(canceled())return;
 let failures=0,renewals=0,lastMessage='';
 while(Date.now()<deadline&&!canceled()){
  $('video-title').textContent='Preparando vídeo…';$('video-message').textContent='Aguardando o gravador'+(result.converted?' e a conversão':'')+'. A imagem abrirá automaticamente.';
  try{
   const r=await request(result.url,{},Math.min(30000,deadline-Date.now()));if(canceled())return;
   if(r.ok){const body=await r.text();if(body.trimStart().startsWith('#EXTM3U'))return result;}
   else{const data=await r.json().catch(()=>({}));lastMessage=data.detail||'';if([401,403,409,422,429].includes(r.status)){const e=Error(lastMessage||'Abertura não autorizada.');e.status=r.status;throw e;}if(/autenticação|permissão|codificador|opção FFmpeg/i.test(lastMessage)){const e=Error(lastMessage);e.status=422;throw e;}}
  }catch(e){if(canceled())return;if(e.status)throw e;}
  failures++;
  if(failures>=3&&renewals<2&&deadline-Date.now()>5000){result=await ticket();if(canceled())return;renewals++;failures=0;}
  if(Date.now()<deadline)await new Promise(resolve=>setTimeout(resolve,Math.min(2000,deadline-Date.now())));
 }
 if(!canceled())throw Error('O vídeo não ficou disponível dentro de 45 segundos. '+(lastMessage||'Verifique o stream e os logs de video e app.'));
}

function volumeIcon(muted){return '<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M11 5 6 9H3v6h3l5 4z"/>'+(muted?'<path d="m16 9 5 6m0-6-5 6"/>':'<path d="M15 8a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14"/>')+'</svg>';}
function updateVolumeIcon(){const muted=$('live-video').muted,b=$('reference-mute');b.innerHTML=volumeIcon(muted);b.title=muted?'Ativar áudio':'Silenciar áudio';b.setAttribute('aria-label',b.title);b.setAttribute('aria-pressed',String(!muted));}
$('reference-mute').onclick=()=>{const v=$('live-video');v.muted=!v.muted;updateVolumeIcon();};
$('live-video').addEventListener('volumechange',updateVolumeIcon);updateVolumeIcon();
$('player-panel').ondblclick=()=>$('fullscreen').click();

let recorderSettingsId=null;
$('configure-recorder-state').onclick=async()=>{if(!editing){toast('Salve primeiro o cadastro do gravador.');return;}const c=cameras.find(x=>x.id===editing);if(!['Intelbras','Hikvision'].includes(c?.manufacturer)||c?.device_type!=='nvr'){toast('Disponível para gravadores Intelbras e Hikvision.');return;}try{const r=await api('/cameras/'+editing+'/recorder-status');recorderSettingsId=editing;const f=$('recorder-state-form');f.elements.enabled.checked=r.enabled;f.elements.web_port.value=r.web_port;f.elements.scheme.value=r.scheme;$('recorder-state-error').textContent='';$('recorder-state-dialog').showModal();}catch(e){toast(e.message);}};
$('close-recorder-state').onclick=()=>$('recorder-state-dialog').close();
$('recorder-state-form').onsubmit=async e=>{e.preventDefault();const f=e.target;try{await api('/cameras/'+recorderSettingsId+'/recorder-status',{method:'PUT',body:JSON.stringify({enabled:f.elements.enabled.checked,web_port:Number(f.elements.web_port.value),scheme:f.elements.scheme.value})});$('recorder-state-dialog').close();toast('Consulta configurada para este gravador. Os estados serão atualizados no próximo ciclo.');}catch(error){$('recorder-state-error').textContent=error.message;}};

$('live-video').addEventListener('timeupdate',()=>{const v=$('live-video');if(!v.hidden&&v.currentTime!==lastVideoTime){lastVideoTime=v.currentTime;lastVideoProgress=Date.now();liveReceivingId=selected;const c=cameras.find(x=>x.id===selected);if(c)renderCameraDetails(c);confirmLivePlayback();}});

setInterval(()=>{if(liveReceivingId&&Date.now()-lastVideoProgress>=5000){liveReceivingId=null;const c=cameras.find(x=>x.id===selected);if(c)renderCameraDetails(c);}},1000);

async function confirmLivePlayback(){
 const video=$('live-video');
 if(!activeLiveTicket||liveConfirming||video.paused||video.readyState<2||Date.now()-lastLiveConfirmation<30000)return;
 const ticket=activeLiveTicket,generation=playGeneration,id=selected;
 liveConfirming=true;lastLiveConfirmation=Date.now();
 try{
  const result=await api('/live-confirm',{method:'POST',headers:{'X-Video-Client':videoClientKey},body:JSON.stringify({ticket})});
  if(generation!==playGeneration||ticket!==activeLiveTicket||id!==selected)return;
  if(result.confirmed&&result.camera_id===id){
   const camera=cameras.find(c=>c.id===id);
   if(camera){camera.status=result.status;camera.checked_at=result.checked_at;camera.verification_stale=false;camera.diagnostic=result.diagnostic;render();}
   await load();
  }
 }catch(error){if(generation===playGeneration&&error.status===409)activeLiveTicket=null;}
 finally{liveConfirming=false;}
}
