'use strict';
// Native Google map. Never fetch Google tiles through Leaflet.
let googleMap=null,googleLoading=null,googleActive=false,googlePins=[],googleDraft=null,googleExpanded=null;
const leafletMap=map,leafletRender=renderMapGroups,leafletBasemap=setBasemap,originalPage=page,originalDraft=setDraftPosition,originalClose=closePositioning;
function googleClear(){googlePins.forEach(p=>p.setMap(null));googlePins=[];}
function googleIcon(status,count){const color=count?'#286da1':({online:'#277c3e',offline:'#cf4343',free:'#929ba5',unknown:'#d3a52d'}[status]||'#929ba5');const text=count?String(count):'▣';const svg='<svg xmlns="http://www.w3.org/2000/svg" width="44" height="50"><path fill="'+color+'" stroke="white" stroke-width="2" d="M22 49L7 31A20 20 0 1 1 37 31Z"/><text x="22" y="26" text-anchor="middle" fill="white" font-family="Arial" font-weight="bold" font-size="16">'+text+'</text></svg>';return {url:'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(svg),scaledSize:new google.maps.Size(33,37.5),anchor:new google.maps.Point(16.5,36.75)};}
function googlePin(c,pos){const pin=new google.maps.Marker({map:googleMap,position:pos,icon:googleIcon(c.status),title:c.name+(c.sector_name?' · '+c.sector_name:''),label:$('map-labels').checked?{text:c.name,color:'#fff',fontSize:'11px'}:null});pin.addListener('click',()=>positioning?choosePositionCamera(c.id):openCamera(c.id));googlePins.push(pin);}
renderMapGroups=function(visible){visible=visible.filter(c=>!c.is_free);if(!googleActive)return leafletRender(visible);if(!googleMap||!googleMap.getProjection())return;googleClear();const projection=googleMap.getProjection(),scale=2**googleMap.getZoom();const points=visible.map(c=>{const p=projection.fromLatLngToPoint(new google.maps.LatLng(c.lat,c.lng));return {x:p.x*scale,y:p.y*scale,camera:c};});groupCameraPoints(points,58).forEach(group=>{if(group.length===1){const c=group[0].camera;googlePin(c,{lat:c.lat,lng:c.lng});return;}const key=group.map(p=>p.camera.id).sort((a,b)=>a-b).join(',');const x=group.reduce((a,p)=>a+p.x,0)/group.length,y=group.reduce((a,p)=>a+p.y,0)/group.length;const pos=projection.fromPointToLatLng(new google.maps.Point(x/scale,y/scale));if(googleExpanded===key){group.forEach((p,i)=>{const a=i*2*Math.PI/group.length,r=Math.max(65,group.length*22/(2*Math.PI));const display=projection.fromPointToLatLng(new google.maps.Point((x+Math.cos(a)*r)/scale,(y+Math.sin(a)*r)/scale));const line=new google.maps.Polyline({map:googleMap,path:[{lat:p.camera.lat,lng:p.camera.lng},display],strokeColor:'#577b99',strokeWeight:1});googlePins.push(line);googlePin(p.camera,display);});return;}const pin=new google.maps.Marker({map:googleMap,position:pos,icon:googleIcon(null,group.length),title:group.length+' câmeras · clique para aproximar'});pin.addListener('click',()=>{if(googleMap.getZoom()>=21){googleExpanded=key;renderMapGroups(filtered());}else{const bounds=new google.maps.LatLngBounds();group.forEach(p=>bounds.extend({lat:p.camera.lat,lng:p.camera.lng}));const max=Math.min(21,googleMap.getZoom()+3);google.maps.event.addListenerOnce(googleMap,'idle',()=>{if(googleMap.getZoom()>max)googleMap.setZoom(max);});googleMap.fitBounds(bounds,65);}});googlePins.push(pin);});};
async function ensureGoogle(){if(googleMap)return;if(googleLoading)return googleLoading;googleLoading=(async()=>{const conf=await api('/maps-config');if(!conf.google_api_key)throw Error('Configure GOOGLE_MAPS_API_KEY no arquivo .env e recrie o serviço app.');await new Promise((resolve,reject)=>{window.schefferGoogleReady=resolve;window.gm_authFailure=()=>{$('map-imagery-status').textContent='Google recusou a chave. Verifique API, faturamento e restrições.';reject(Error('Google recusou a chave de API.'));};const script=document.createElement('script');script.src='https://maps.googleapis.com/maps/api/js?'+new URLSearchParams({key:conf.google_api_key,loading:'async',callback:'schefferGoogleReady',v:'quarterly',language:'pt-BR',region:'BR'});script.onerror=()=>reject(Error('Não foi possível carregar Google Maps. Verifique internet.'));document.head.appendChild(script);});googleMap=new google.maps.Map($('google-map'),{center:{lat:center[0],lng:center[1]},zoom:17,maxZoom:21,mapTypeId:'satellite',tilt:0,streetViewControl:false,mapTypeControl:false});googleMap.addListener('idle',()=>{if(googleActive)renderMapGroups(filtered());});googleMap.addListener('zoom_changed',()=>googleExpanded=null);googleMap.addListener('click',e=>{googleExpanded=null;if(positioning&&!positionSaving&&positionCameraId)setDraftPosition(e.latLng.lat(),e.latLng.lng());else renderMapGroups(filtered());});})().finally(()=>googleLoading=null);return googleLoading;}
const googleAdapter={invalidateSize(){if(googleMap)google.maps.event.trigger(googleMap,'resize');},panTo(p){if(googleMap)googleMap.panTo({lat:p[0],lng:p[1]});},setView(p,z){if(googleMap){googleMap.setCenter(Array.isArray(p)?{lat:p[0],lng:p[1]}:p);googleMap.setZoom(z);}},getZoom(){return googleMap?.getZoom()||17;},removeLayer(layer){if(layer===draftMarker){googleDraft?.setMap(null);googleDraft=null;}else leafletMap?.removeLayer(layer);}};
let googleProviderRequest=0;
setBasemap=async function(name){if(positionSaving)return;const request=++googleProviderRequest;if(positioning)closePositioning();if(name!=='google'){googleActive=false;map=leafletMap;$('google-map').hidden=true;$('map').hidden=false;leafletBasemap(name);map?.invalidateSize();render();return;}if($('map-page').hidden){try{localStorage.setItem('scheffer-basemap','google');}catch{}return;}$('map-imagery-status').textContent='Carregando Google Satélite…';try{await ensureGoogle();if(request!==googleProviderRequest||$('map-page').hidden)return;googleActive=true;map=googleAdapter;$('map').hidden=true;$('google-map').hidden=false;$('map-fallback').hidden=true;$('satellite-detail-control').hidden=true;$('map-basemap').value='google';$('map-imagery-status').textContent='Google Satélite · detalhes conforme cobertura disponível';clearTimeout(basemapTimer);try{localStorage.setItem('scheffer-basemap','google');}catch{}map.invalidateSize();render();}catch(e){$('map-basemap').value=googleActive?'google':activeBasemap===basemaps.streets?'streets':'satellite';$('map-imagery-status').textContent=e.message;toast(e.message);}};
page=function(name){originalPage(name);if(name==='map'){let preferred;try{preferred=localStorage.getItem('scheffer-basemap');}catch{}if(preferred==='google')setBasemap('google');}};
setDraftPosition=function(lat,lng){if(!googleActive)return originalDraft(lat,lng);if(!Number.isFinite(lat)||!Number.isFinite(lng)||lat<-90||lat>90||lng<-180||lng>180){$('position-message').textContent='Coordenadas inválidas.';return;}$('position-lat').value=lat.toFixed(7);$('position-lng').value=lng.toFixed(7);if(googleDraft)googleDraft.setPosition({lat,lng});else{googleDraft=new google.maps.Marker({map:googleMap,position:{lat,lng},draggable:true,zIndex:2000,icon:googleIcon('unknown'),title:'Nova posição — salve para confirmar'});googleDraft.addListener('dragend',e=>setDraftPosition(e.latLng.lat(),e.latLng.lng()));}draftMarker={dragging:{disable(){googleDraft?.setDraggable(false);},enable(){googleDraft?.setDraggable(true);}},getLatLng(){const p=googleDraft.getPosition();return {lat:p.lat(),lng:p.lng()};}};};
closePositioning=function(){originalClose();if(!positionSaving){googleDraft?.setMap(null);googleDraft=null;}};
// Landing screen avoids creating a billable Google map before an explicit visit.
page('dashboard');
// Automatic mode: Google is instantiated only at zoom 17 or above.
let googleAutoSwitch=false;
const autoLabel=document.createElement('label');autoLabel.innerHTML='<input type="checkbox" id="google-at-max"> Google a partir do zoom 17';$('map-basemap').closest('.map-controls').appendChild(autoLabel);
try{$('google-at-max').checked=localStorage.getItem('scheffer-google-at-max')!=='false';}catch{$('google-at-max').checked=true;}
function persistGoogleAuto(){try{localStorage.setItem('scheffer-google-at-max',String($('google-at-max').checked));}catch{}}
$('google-at-max').onchange=persistGoogleAuto;
async function activateGoogleAtZoom(){if(!$('google-at-max').checked||googleActive||googleAutoSwitch||$('map-page').hidden||activeBasemap!==basemaps.satellite||leafletMap.getZoom()<17)return;googleAutoSwitch=true;const focus=leafletMap.getCenter(),targetZoom=leafletMap.getZoom();try{await setBasemap('google');if(googleActive){googleMap.setCenter({lat:focus.lat,lng:focus.lng});googleMap.setZoom(targetZoom);}}finally{googleAutoSwitch=false;}}
leafletMap?.on('zoomend',activateGoogleAtZoom);
const originalEnsureGoogle=ensureGoogle;
ensureGoogle=async function(){await originalEnsureGoogle();if(googleMap.__schefferAuto)return;googleMap.__schefferAuto=true;googleMap.addListener('zoom_changed',()=>{if(!googleActive||!$('google-at-max').checked||googleAutoSwitch||googleMap.getZoom()>=17)return;const p=googleMap.getCenter(),z=googleMap.getZoom();setBasemap('satellite');leafletMap.setView([p.lat(),p.lng()],z);});};
// In automatic mode a new session starts on Esri, regardless of last provider.
if($('google-at-max').checked){try{localStorage.setItem('scheffer-basemap','streets');}catch{}}

// Every new page session starts with Streets, independent of last selection.
try{localStorage.setItem('scheffer-basemap','streets');}catch{}
leafletBasemap('streets');
const pageWithGoogle=page;
page=function(name){pageWithGoogle(name);if(name==='map')activateGoogleAtZoom();};

const setBasemapWithGoogle=setBasemap;
setBasemap=async function(name){await setBasemapWithGoogle(name);if(name==='satellite')activateGoogleAtZoom();};
